version: '3.8'

services:
  zonaprop-scraper:
    build: .
    container_name: zonaprop-scraper
    environment:
      - PUBLIC_URL=https://catalogo.korvance.com
      - AGENCY_WHATSAPP=+5491112345678
      - NODE_ENV=production
    shm_size: '1gb'
    networks:
      - korvancenet
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        # Subdominio genérico modificado:
        - "traefik.http.routers.zonascraper.rule=Host(`catalogo.korvance.com`)"
        - "traefik.http.routers.zonascraper.entrypoints=websecure"
        - "traefik.http.routers.zonascraper.tls=true"
        - "traefik.http.routers.zonascraper.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.zonascraper.loadbalancer.server.port=3000"
        - "traefik.docker.network=korvancenet"

networks:
  korvancenet:
    external: true
